services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  backend:
    build:
      context: .
    command: >
      sh -c "
        alembic upgrade head && 
        uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@db:5432/users
    depends_on:
      - db
    networks:
      - backend_net

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - backend_net  

  rag-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
    networks:
      - backend_net  

volumes:
  postgres_data:

networks:
  backend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
