version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # Используем только привязку тома
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:admin@db:5432/users
    depends_on:
      db:
        condition: service_healthy # Указываем условие
    networks:
      - backend_net

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - backend_net

  rag-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
    networks:
      - backend_net

# volumes: #  Удаляем лишнюю секцию volumes
  # postgres_data:

networks:
  backend_net:
    driver: bridge
    # ipam: #  Удаляем фикс. IP (если нет необходимости)
    #   config:
    #     - subnet: 192.168.100.0/24
