"""Add tg_id to User model


Revision ID: ca10fe73b7c7
Revises: 5b4e8f87c365
Create Date: 2025-08-01 09:34:35.236185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca10fe73b7c7'
down_revision: Union[str, None] = '5b4e8f87c365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###
